# Generated by Django 5.2.8 on 2025-12-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('step_payment', 'Оплата за шаги'), ('money_deduction', 'Вычет денег'), ('correction', 'Коррекция'), ('refund', 'Возврат'), ('other', 'Другое')], max_length=50, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (£)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс до')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после')),
                ('algorithm', models.CharField(blank=True, max_length=100, verbose_name='Алгоритм')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='ID источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требует подтверждения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Обработано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина удаления')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('original_data', models.JSONField(default=dict, verbose_name='Оригинальные данные')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='transactions.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Лог удаления транзакции',
                'verbose_name_plural': 'Логи удаления транзакций',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_f5864b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_ed11cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['algorithm'], name='transaction_algorit_9ec57d_idx'),
        ),
    ]
