# Generated by Django 5.2.8 on 2025-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_f5864b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_transac_ed11cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_algorit_9ec57d_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс после'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс до'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина/Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Пополнение'), ('deduction', 'Вычет'), ('step_payment', 'Оплата за шаги'), ('other', 'Другое')], max_length=20, verbose_name='Тип транзакции'),
        ),
    ]
