# Generated by Django 5.2.8 on 2025-12-10 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_transaction_user_id_f5864b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='transactiondeletionlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина удаления'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status', 'is_deleted'], name='transaction_user_id_322716_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondeletionlog',
            index=models.Index(fields=['deleted_by', 'deleted_at'], name='transaction_deleted_519155_idx'),
        ),
    ]
