# Generated by Django 5.2.8 on 2025-12-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Виртуальный баланс (£)')),
                ('steps_balance', models.IntegerField(default=0, verbose_name='Общее количество шагов')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего заработано (£)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
