# Generated by Django 5.2.8 on 2025-12-04 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего вычтено (£)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Виртуальный баланс (£)'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (£)')),
                ('transaction_type', models.CharField(choices=[('income', 'Начисление'), ('deduction', 'Вычет'), ('correction', 'Коррекция')], max_length=20, verbose_name='Тип операции')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
