# Generated by Django 5.2.8 on 2025-12-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDeductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вычета (£)')),
                ('reason', models.TextField(verbose_name='Причина вычета')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс до вычета')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после вычета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вычета')),
                ('deducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_deductions', to=settings.AUTH_USER_MODEL, verbose_name='Вычет произведен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог вычета денег',
                'verbose_name_plural': 'Логи вычетов денег',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
