# Generated by Django 5.2.8 on 2025-12-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_moneydeductionlog_delete_algorithm_delete_eventtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydeductionlog',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='Причина удаления'),
        ),
        migrations.AddField(
            model_name='moneydeductionlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='moneydeductionlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_deductions', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='moneydeductionlog',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='Причина удаления'),
        ),
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем'),
        ),
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.CreateModel(
            name='PaymentDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина удаления')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оригинальная сумма')),
                ('original_created_at', models.DateTimeField(verbose_name='Оригинальная дата создания')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_payment_logs', to=settings.AUTH_USER_MODEL, verbose_name='Оригинальный пользователь')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='algorithms.steppaymentalgorithm', verbose_name='Удаленная запись')),
            ],
            options={
                'verbose_name': 'Лог удаления выплаты',
                'verbose_name_plural': 'Логи удаления выплат',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
