# Generated by Django 5.2.8 on 2025-12-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_moneydeductionlog_delete_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='delete_reason',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='steppaymentalgorithm',
            name='processed_by',
        ),
    ]
