# Generated by Django 5.2.8 on 2025-12-10 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0004_remove_steppaymentalgorithm_delete_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='steppaymentalgorithm',
            name='processed',
            field=models.BooleanField(default=True, verbose_name='Обработано'),
        ),
        migrations.AddIndex(
            model_name='moneydeductionlog',
            index=models.Index(fields=['user', '-created_at'], name='algorithms__user_id_793301_idx'),
        ),
        migrations.AddIndex(
            model_name='moneydeductionlog',
            index=models.Index(fields=['is_deleted', 'created_at'], name='algorithms__is_dele_c8822e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdeletionlog',
            index=models.Index(fields=['payment'], name='algorithms__payment_db51c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdeletionlog',
            index=models.Index(fields=['original_user', '-deleted_at'], name='algorithms__origina_b700bc_idx'),
        ),
        migrations.AddIndex(
            model_name='steppaymentalgorithm',
            index=models.Index(fields=['user', 'processed'], name='algorithms__user_id_6c8d76_idx'),
        ),
        migrations.AddIndex(
            model_name='steppaymentalgorithm',
            index=models.Index(fields=['is_deleted', 'created_at'], name='algorithms__is_dele_5c322b_idx'),
        ),
    ]
