# Generated by Django 5.2.8 on 2025-12-11 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_steppaymentalgorithm_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребёнок'), ('sibling', 'Брат/сестра'), ('cousin', 'Двоюродный брат/сестра'), ('aunt_uncle', 'Тётя/дядя'), ('other', 'Другое')], max_length=20)),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('is_close_relative', models.BooleanField(default=False, help_text='Близкий родственник: родители, дети, братья/сёстры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Семейный член',
                'verbose_name_plural': 'Семейные члены',
            },
        ),
    ]
